Add a link to the slc CLI app
plaintextaccounting/plaintextaccounting.github.io pull request #92
Opened 2021-03-23 15:07 UTC by marvinpinto

`slc` is a CLI application to generate Ledger accounting entries, works with generic CSV files as well as the Stripe API.

This also removes `ledger-reconciler` since that project is no-longer maintained.

2021-03-24 16:03 UTC, colindean requested changes
👍 

I'm cool with removing `ledger-reconciler` since you're its author!

2021-03-24 16:03 UTC, colindean commented on index.md
> +- [slc](https://github.com/marvinpinto/slc) slc is a CLI application to generate Ledger accounting entries, works with generic CSV files as well as the Stripe API
```suggestion
- [slc](https://github.com/marvinpinto/slc) generates Ledger accounting entries, works with generic CSV files as well as the Stripe API
```

2021-03-24 16:03 UTC, colindean commented on index.html
> +<li><a href="https://github.com/marvinpinto/slc">slc</a> slc is a CLI application to generate Ledger accounting entries, works with generic CSV files as well as the Stripe API</li>
```suggestion
<li><a href="https://github.com/marvinpinto/slc">slc</a> generates Ledger accounting entries, works with generic CSV files as well as the Stripe API</li>
```

2021-03-24 16:03 UTC, colindean commented on index1.html
> +<li><a href="https://github.com/marvinpinto/slc">slc</a> slc is a CLI application to generate Ledger accounting entries, works with generic CSV files as well as the Stripe API</li>
```suggestion
<li><a href="https://github.com/marvinpinto/slc">slc</a> generates Ledger accounting entries, works with generic CSV files as well as the Stripe API</li>
```

2021-03-24 16:37 UTC, colindean requested changes
Thanks! Avoid doubling the name of the program, following convention from other lines.

2021-03-24 16:37 UTC, colindean commented on index.html
> +<li><a href="https://github.com/marvinpinto/slc">slc</a> slc generates Ledger accounting entries, works with generic CSV files as well as the Stripe API</li>
```suggestion
<li><a href="https://github.com/marvinpinto/slc">slc</a> generates Ledger accounting entries, works with generic CSV files as well as the Stripe API</li>
```

2021-03-24 16:37 UTC, colindean commented on index.md
> +- [slc](https://github.com/marvinpinto/slc) slc generates Ledger accounting entries, works with generic CSV files as well as the Stripe API
```suggestion
- [slc](https://github.com/marvinpinto/slc) generates Ledger accounting entries, works with generic CSV files as well as the Stripe API
```

2021-03-24 16:37 UTC, colindean commented on index1.html
> +<li><a href="https://github.com/marvinpinto/slc">slc</a> slc generates Ledger accounting entries, works with generic CSV files as well as the Stripe API</li>
```suggestion
<li><a href="https://github.com/marvinpinto/slc">slc</a> generates Ledger accounting entries, works with generic CSV files as well as the Stripe API</li>
```

2021-03-24 19:38 UTC, colindean approved these changes

2021-03-24 19:38 UTC, merged

2021-03-25 15:29 UTC, simonmichael commented
Thanks! index1.html was old cruft ("This is the pre-2019-reorg version of index.html, for comparison; don't edit this."). I have removed it for clarity.